[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[soldeer]
recursive_deps = true

[dependencies]
forge-std = "1.9.6"
test-project-foo = "0.0.2"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
